// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AndroidIcon: typeof import('./components/icons/AndroidIcon.vue')['default']
    AngularIcon: typeof import('./components/icons/AngularIcon.vue')['default']
    APIIcon: typeof import('./components/icons/APIIcon.vue')['default']
    App: typeof import('./components/App.vue')['default']
    AWSIcon: typeof import('./components/icons/AWSIcon.vue')['default']
    ChromeIcon: typeof import('./components/icons/ChromeIcon.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    CordovaIcon: typeof import('./components/icons/CordovaIcon.vue')['default']
    CSSIcon: typeof import('./components/icons/CSSIcon.vue')['default']
    DarkModeToggler: typeof import('./components/DarkModeToggler.vue')['default']
    DockerIcon: typeof import('./components/icons/DockerIcon.vue')['default']
    DownloadIcon: typeof import('./components/icons/DownloadIcon.vue')['default']
    DynamicIcon: typeof import('./components/icons/DynamicIcon.vue')['default']
    ElectronIcon: typeof import('./components/icons/ElectronIcon.vue')['default']
    FacebookIcon: typeof import('./components/icons/FacebookIcon.vue')['default']
    GameBoyAdvanceIcon: typeof import('./components/icons/GameBoyAdvanceIcon.vue')['default']
    GithubIcon: typeof import('./components/icons/GithubIcon.vue')['default']
    GooglePlayIcon: typeof import('./components/icons/GooglePlayIcon.vue')['default']
    HandlebarsIcon: typeof import('./components/icons/HandlebarsIcon.vue')['default']
    HTMLIcon: typeof import('./components/icons/HTMLIcon.vue')['default']
    Icon: typeof import('./components/icons/Icon.vue')['default']
    InstagramIcon: typeof import('./components/icons/InstagramIcon.vue')['default']
    Intro: typeof import('./components/Intro.vue')['default']
    JavaIcon: typeof import('./components/icons/JavaIcon.vue')['default']
    JavaScriptIcon: typeof import('./components/icons/JavaScriptIcon.vue')['default']
    LinkedInIcon: typeof import('./components/icons/LinkedInIcon.vue')['default']
    LinuxIcon: typeof import('./components/icons/LinuxIcon.vue')['default']
    MacIcon: typeof import('./components/icons/MacIcon.vue')['default']
    MongoDBIcon: typeof import('./components/icons/MongoDBIcon.vue')['default']
    MoonIcon: typeof import('./components/icons/MoonIcon.vue')['default']
    MySQLIcon: typeof import('./components/icons/MySQLIcon.vue')['default']
    NETIcon: typeof import('./components/icons/NETIcon.vue')['default']
    NodeIcon: typeof import('./components/icons/NodeIcon.vue')['default']
    PayPalIcon: typeof import('./components/icons/PayPalIcon.vue')['default']
    PHPIcon: typeof import('./components/icons/PHPIcon.vue')['default']
    PostgresSQLIcon: typeof import('./components/icons/PostgresSQLIcon.vue')['default']
    Project: typeof import('./components/Project.vue')['default']
    PythonIcon: typeof import('./components/icons/PythonIcon.vue')['default']
    ReactIcon: typeof import('./components/icons/ReactIcon.vue')['default']
    SassIcon: typeof import('./components/icons/SassIcon.vue')['default']
    StripeIcon: typeof import('./components/icons/StripeIcon.vue')['default']
    StylusIcon: typeof import('./components/icons/StylusIcon.vue')['default']
    SunIcon: typeof import('./components/icons/SunIcon.vue')['default']
    TwitterIcon: typeof import('./components/icons/TwitterIcon.vue')['default']
    TypeScriptIcon: typeof import('./components/icons/TypeScriptIcon.vue')['default']
    VueIcon: typeof import('./components/icons/VueIcon.vue')['default']
    WebIcon: typeof import('./components/icons/WebIcon.vue')['default']
    WindowsIcon: typeof import('./components/icons/WindowsIcon.vue')['default']
  }
}
