version: "3.9"

services:
    alanmorel:
        container_name: alanmorel
        image: alanmorel
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
            args:
                ENV: ${NODE_ENV}
        environment:
            DOCKER: "true"
        volumes:
            - "./logs:/app/logs"
            - "./images:/app/images"
        expose:
            - "${PORT}"
        networks:
            - docker

networks:
    docker:
        external: true
