services:
    alanmorel:
        container_name: alanmorel
        image: alanmorel
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        volumes:
            - ./logs:/usr/src/app/logs
            - ./files:/usr/src/app/files
            - ./entries:/usr/src/app/entries
        expose:
            - "${PORT}"
        networks:
            - docker

networks:
    docker:
        external: true
