version: "3.9"

services:
    alanmorel:
        container_name: alanmorel
        image: alanmorel
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        volumes:
            - "./logs:/app/logs"
            - "./files:/app/files"
            - "./entries:/app/entries"
        expose:
            - "${PORT}"
        networks:
            - docker

networks:
    docker:
        external: true
