version: "3.9"

services:
    alanmorel:
        container_name: alanmorel
        image: alanmorel
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - "./logs:/app/logs"
            - "./images:/app/images"
        env_file:
            - ./.env.docker
        restart: always
        expose:
            - "${PORT}"
        networks:
            - docker

networks:
    docker:
        external: true
